app:
    resource: '@AppBundle/Controller/'
    type: annotation

coop_tilleuls_forgot_password:
    resource: '@CoopTilleulsForgotPasswordBundle/Resources/config/routing.xml'
    prefix:   '/forgot_password'